### ISSUE TITLE
fails to build on windows with 0.14.0 nightly

### ISSUE THREAD

**Issue by mk2s** [kristoff-it/zine#117]
\zine\src\exes\server\watcher\WindowsWatcher.zig:84:20: error: root source file struct 'os.windows' has no member named 'FILE_NOTIFY_CHANGE_LAST_WRITE_TIME'
            windows.FILE_NOTIFY_CHANGE_LAST_WRITE_TIME | windows.FILE_NOTIFY_CHANGE_FILE_NAME | windows.FILE_NOTIFY_CHANGE_DIR_NAME,
            ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

os.windows changed interface https://github.com/ziglang/zig/pull/20667 in July 2024

PR https://github.com/kristoff-it/zine/pull/116 fixes the issue

**Comment by kristoff-it** [comment]
fixed in #116
