### ISSUE TITLE
Add support for OpenBSD

### ISSUE THREAD

**Issue by istilla** [kristoff-it/zine#112]
Ziggy, SuperMD and SuperHTML currently build with OpenBSD's Zig 0.13.0 port.

```
$ uname -mrsv
OpenBSD 7.6 GENERIC.MP#280 arm64
$ zig version
0.13.0+cf90dfd30
```
Attempts to build Zine's sample site result in:

```
$ git clone https://github.com/kristoff-it/zine-ssg.io.git
$ cd zine-ssg.io
$ zig build serve
serve
└─ run server
   └─ zig build-exe server ReleaseFast native 1 errors
~/.cache/zig/p/122049c99f3faaaff159cdccb3792d1518b10534e8225e26e5b24a369d325b0ebdc5/src/exes/server/Reloader.zig:13:13: error: unsupported platform
    else => @compileError("unsupported platform"),
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    Reloader: ~/.cache/zig/p/122049c99f3faaaff159cdccb3792d1518b10534e8225e26e5b24a369d325b0ebdc5/src/exes/server/Reloader.zig:23:10
    Reloader: ~/.cache/zig/p/122049c99f3faaaff159cdccb3792d1518b10534e8225e26e5b24a369d325b0ebdc5/src/exes/server/Reloader.zig:1:18
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
error: the following command failed with 1 compilation errors:
/usr/local/bin/zig build-exe -OReleaseFast --dep options --dep mime --dep ws -Mroot=~/.cache/zig/p/122049c99f3faaaff159cdccb3792d1518b10534e8225e26e5b24a369d325b0ebdc5/src/exes/server/main.zig -Moptions=~/zine-ssg.io/.zig-cache/c/e38aacef8f649d6376814be6b2c14a79/options.zig -OReleaseFast -Mmime=~/.cache/zig/p/12209083b0c43d0f68a26a48a7b26ad9f93b22c9cff710c78ddfebb47b89cfb9c7a4/mime.zig -Mws=~/.cache/zig/p/12208720b772330f309cfb48957f4152ee0930b716837d0c1d07fee2dea2f4dc712e/src/websocket.zig --cache-dir ~/zine-ssg.io/.zig-cache --global-cache-dir ~/.cache/zig --name server --listen=-
Build Summary: 94/97 steps succeeded; 1 failed (disable with --summary none)
serve transitive failure
└─ run server transitive failure
   └─ zig build-exe server ReleaseFast native 1 errors
error: the following build command failed with exit code 1:
~/zine-ssg.io/.zig-cache/o/f24d34fb5a545dd4cd08295c99ca27c5/build /usr/local/bin/zig ~/zine-ssg.io ~/zine-ssg.io/.zig-cache ~/.cache/zig --seed 0xec9ea060 -Z16befcb5243abf98 serve
```

**Comment by kristoff-it** [comment]
I'd be happy to merge support for OpenBSD. The error seen there is the fact that we don't have file watching implemented for OpenBSD.


The task is to add a new watcher in https://github.com/kristoff-it/zine/tree/main/src/exes/server/watcher (and then wire it into `Reloader.zig`), that's pretty much it.

**Comment by kristoff-it** [comment]
The Zig compiler has an implementation of file watching based on kqueue: 

https://github.com/ziglang/zig/blob/1f92b394e97ce13e49cce8838968c0dc848d0abb/lib/std/Build/Watch.zig#L603

Related to the code above is this discussion where macOS users are reporting that the kqueue implementation has trouble with edits made by VSCode and Zed because of a missing feature in macOS' kqueue:

https://github.com/ziglang/zig/issues/21905

In our case we don't have to worry about macOS since it has a native implementation, meaning that we would want to use `NOTE.CLOSE_WRITE`. 

Lastly, note that the code linked above contains a bug fixed here https://github.com/ziglang/zig/pull/23247.

**Comment by LowByteFox** [comment]
I could possibly take a look at this issue, maybe try and help but for that I'll need OpenBSD-current and I have OpenBSD-7.6

I could perform `sysupgrade -s` but only once I get home, in case something breaks, get zig-0.14.0 and try to get it to work

**Comment by LowByteFox** [comment]
Okay, so far there is an issue with `zig_yaml` which can be easily fixed by letting `zig build` crash, and then edit the `build.zig` from the cache and remove this part from the end of the `build.zig`.
```zig
    const enable_spec_tests = b.option(bool, "enable-spec-tests", "Enable YAML Test Suite") orelse false;
    if (!enable_spec_tests) {
        const gen = SpecTest.create(b);
        var spec_tests = b.addTest(.{
            .root_source_file = gen.path(),
            .target = target,
            .optimize = optimize,
        });
        spec_tests.root_module.addImport("yaml", yaml_module);
        test_step.dependOn(&b.addRunArtifact(spec_tests).step);
    }
```
possibly just change the line to
```zig
_ = b.option(bool, "enable-spec-tests", "Enable YAML Test Suite") orelse false;
```

I will work on this from time to time, get as much implemented as the OS is capable of, the progress can be tracked on my [fork](https://github.com/LowByteFox/zine). I'll create a separate branch just in case.

**Comment by Spiffyk** [comment]
Note: This should probably be reopened - GitHub saw `but does not fix #112.` in 62a2c15, only took the `fix #112` substring as a directive and closed the issue errorneously.
