### ISSUE TITLE
bug: unable to build zine-ssg.io on a fresh build

### ISSUE THREAD

**Issue by ethanholz** [kristoff-it/zine#41]
I attempted to use the docs to build and test `zine-ssg.io`. However, when I attempt to run this as is, I get the following error on both macOS and Linux running with Zig 0.13.0:
```shell
/Users/ethan/.cache/zig/p/1220c7a5284269c9aca520c601438155d81dc4e27cb79696b6648aef24686d4c942d/build.zig:290:25: error: no module named 'zig-afl-kit' available within module root.@dependencies.1220c7a5284269c9aca520c601438155d81dc4e27cb79696b6648aef24686d4c942d
    const afl = @import("zig-afl-kit");
                        ^~~~~~~~~~~~~
referenced by:
    build: /Users/ethan/.cache/zig/p/1220c7a5284269c9aca520c601438155d81dc4e27cb79696b6648aef24686d4c942d/build.zig:248:5
    runBuild__anon_16353: /nix/store/59c7cd6llbcg4zjvgymppcgab54qpv26-zig-0.13.0/lib/std/Build.zig:2117:37
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/Users/ethan/.cache/zig/p/1220a064034f7b797618a1fc5c2f3596b5dbfe4f309afd0798cfc77bbea6bb5eb672/build.zig:2:21: error: no module named 'zig-afl-kit' available within module root.@dependencies.1220a064034f7b797618a1fc5c2f3596b5dbfe4f309afd0798cfc77bbea6bb5eb672
```

Interestingly, when I build using zine version 0.1.0 this build completely fine and subsequent builds work fine. I am guessing this is likely due to an issue with caching `zig-afl-kit` happening incorrectly. Furthermore, if you remove the `.zig-cache` directory, this error will once again propagate. `zine` is able to build standalone, but the site is not able to be built. Feel free to let me know if I can help to work through this!

**Comment by kristoff-it** [comment]
Yes sorry that's on me, first time working with lazy dependencies and I didn't do it properly, fix incoming (you can use a previous version of zine in the meantime).

**Comment by kristoff-it** [comment]
if you fetch the latest commit now you will find that everything works now. I'll add an entry in the website's changelog tomorrow (kinda late here now) but as a quick upgrade guide:

- Update zine: `zig fetch  --save git+https://github.com/kristoff-it/zine`
- In your `build.zig`:
  - change `addWebsite` to `website`
  - remove the `try`

**Comment by ethanholz** [comment]
No worries! I just wanted to make sure it was on your radar. New changes seem to be working well and speed up the compile time!

**Comment by kristoff-it** [comment]
Fixed in v0.2.0, please reopen this issue if you still can reproduce the problem :^)
